import '../globals.css';
import { Inter } from '@next/font/google';
import LocalFont from '@next/font/local';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const calSans = LocalFont({
  src: '../public/fonts/CalSans-SemiBold.ttf',
  variable: '--font-calsans',
});
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={[inter.variable, calSans.variable].join(' ')}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
