import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import { AboutSection } from '../components/about';
import { ContactSection } from '../components/contact';
import { ExperienceSection } from '../components/experience';
import { FooterSection } from '../components/footer';
import { HeroSection } from '../components/hero';
import { ProjectSection } from '../components/projects';
import { Header } from '../components/ui';

export default function Home() {
  return (
    <Box
      w="100%"
      minH="100vh"
      scrollBehavior="smooth"
      position="relative"
      top={0}
      left={0}
    >
      <Head>
        <title>Portfolio | Santiago Pacini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <HeroSection />

      <AboutSection />
      <ExperienceSection />
      <ProjectSection />
      <ContactSection />
      <FooterSection />
    </Box>
  );
}
