import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import Header from '../components/Header';
import {
  AboutSection,
  ContactSection,
  FooterSection,
  HeroSection,
  ProjectSection,
  ExperienceSection,
} from '../components/Sections';

export default function Home() {
  return (
    <Box w="100%" minH="100vh" scrollBehavior="smooth">
      <Head>
        <title>Portfolio | Santiago Pacini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <AboutSection />
      <ExperienceSection />
      <ProjectSection />
      <ContactSection />
      <FooterSection />
    </Box>
  );
}
