import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import Header from '../components/Header';
import AboutSection from '../components/Sections/AboutSection';
import ContactSection from '../components/Sections/ContactSection';
import Footer from '../components/Sections/FooterSection';
import HeroSection from '../components/Sections/HeroSection';
import ProjectSection from '../components/Sections/ProjectSection';

export default function Home() {
  return (
    <Box w="100%" minH="100vh" scrollBehavior="smooth">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeroSection />
      <AboutSection />
      <ProjectSection />
      <ContactSection />
      <Footer />
    </Box>
  );
}
